### PR TITLE
background image

### PR DESCRIPTION
**Pull request by bellalyuxe**

### CODE REVIEW

**Comment by alex-berezovsky** [comment]
Better background

**Review by SugjuChoi — COMMENTED** [review]
clean code for front end changes

**Review by alex-berezovsky — COMMENTED** [review]
Everything works

**Review by alex-berezovsky — COMMENTED** [review]
Everything looks nice

**Comment by joanna985** [comment]
Great job.

**Comment by JPARK1220** [comment]
Code looks clean, will try to document afterwards.

**Comment by sredford6** [comment]
I like the look of the new background.

**Review by sredford6 — COMMENTED** [review]
The new background looks good.

**Pull request merged**
