### PR TITLE
Origin/submit questionnairs

### PR DESCRIPTION
**Pull request by SugjuChoi**

### CODE REVIEW

**Review by bellalyuxe — COMMENTED** [review]
Good work in fixing the questionnaire submission issue.

**Comment by alex-berezovsky** [comment]
Questionnaire submission issue fixed

**Review by alex-berezovsky — COMMENTED** [review]
Looks good

**Comment by JPARK1220** [comment]
Fix to questionnaire submission looks good.

**Comment by sredford6** [comment]
Successfully fixed issue in which users were unable to submit questionnaire after questionnaires were made available at all times. Looks good.

**Review by sredford6 — COMMENTED** [review]
Successfully fixed issue in which users were unable to submit questionnaire after questionnaires were made available at all times. Looks good.

**Pull request merged**
