### PR TITLE
back button

### PR DESCRIPTION
**Pull request by bellalyuxe**

### CODE REVIEW

**Comment by SugjuChoi** [comment]
Looks good - why did the back button get reverted?

**Comment by alex-berezovsky** [comment]
Fixed issue with back button, confirmed

**Comment by joanna985** [comment]
Looks good.

**Review by SugjuChoi — COMMENTED** [review]
clean UI and fix. nice job.

**Comment by joanna985** [comment]
Great work.

**Comment by JPARK1220** [comment]
The questionnaire looks much more flexible now. Good job!

**Pull request merged**
